apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-microservice
  template:
    metadata:
      labels:
        app: java-microservice
    spec:
      containers:
        - name: java-app
          image: barathkumar29/devsecops-java:v1
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: my-dockerhub-secret  